### PR TITLE
fix(core/rust) Handle touchStop event in brightess dialog

### LINKED ISSUE #4261: No instruction to Swipe up after changing brightness T3T1
**Describe the bug**
In order to confirm brightness changes on Trezor, user needs to Swipe up, but no instructions are provided.

This photo is after change was made with horizontal slider:

IMG_6879

User can still swipe up to continue, but he needs to guess this is a correct next step.

**Info:**
 - Suite version: desktop 24.10.1 (3cbe786b5c8effd03b331faec20a41ef01d6671b)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.10.1 Chrome/126.0.6478.234 Electron/31.6.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.3 regular (revision 7f373ae71eca855dd41b4a0fdcc7cadaa13a8281)
 - Transport: BridgeTransport 2.0.33
 
**To Reproduce**
1. Go to Settings -> Device -> Change brightness
2. On Trezor, swipe horizontally to adjust brightness
3. No Swipe up instructions appear at the bottom.

**Expected behavior**
After brightness was changed with slider, **Adjust Swipe horizontally** instructions should change to **Swipe up**

[Figma](https://www.figma.com/design/n43caWJFGJlT167AQcxruu/%E3%80%94-Prod-%E3%80%95Safe-5?node-id=6308-903&t=uhg19qECz8gsHMfn-4):

Screenshot 2024-10-15 at 15 20 34

### PR DESCRIPTION
**Pull request by bieleluk**
This PR adds handling of the `TouchStop` event for `NumberInputSliderDialog` struct on T3T1 (resolves #4261). 

Changes include:

1. In `NumberInputSliderDialog` event function, handling of the `None` value (`TouchEnd` event in `NumberInputSlider` ) is added. It fixes the logic, when the _Adjust_ or _Apply_ strings are shown to the user.

### CODE REVIEW

File: core/embed/rust/src/ui/model_mercury/component/number_input_slider.rs [hunk 1]
```diff
@@ -76,24 +76,27 @@ impl Component for NumberInputSliderDialog {
...
-                self.footer
-                    .update_instruction(ctx, TR::instructions__swipe_horizontally);
-                self.footer.update_description(ctx, TR::setting__adjust);
-                ctx.request_paint();
-            } else {
-                self.footer
-                    .update_instruction(ctx, TR::instructions__swipe_up);
-                self.footer.update_description(ctx, TR::setting__apply);
-                ctx.request_paint();
+        match msg_opt {
```
Comment (mmilata) [inline core/embed/rust/src/ui/model_mercury/component/number_input_slider.rs:93]: Nit: if you wanted to use less lines:
```rust
        msg_opt.map(|value| {
            self.val = value;
            Self::Msg::Changed(value)
        })
```
But I'm personally fine with the current state.

**Review by mmilata — APPROVED** [review]
Looks good to me, thanks for the fix! Briefly tested and it looks like it resolves the problem.

File: core/embed/rust/src/ui/model_mercury/component/number_input_slider.rs (hunk 1 above)
Comment (bieleluk) [reply core/embed/rust/src/ui/model_mercury/component/number_input_slider.rs]: [921e065](https://github.com/trezor/trezor-firmware/pull/4279/commits/921e06552aae9ff0854a49e53425fda65f023f80)

**Review by mmilata — APPROVED** [review]
Please rebase (and squash) the PR & merge it if CI passes.

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: desktop 24.11.0 (bef8f3c4378237d4cf63580d4ab50756f56e3ec1)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/24.11.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.4 regular (revision 3c468fa4ddb0dc28ff7476c6312721babbf71410)
 - Transport: BridgeTransport 3.0.0-bundled.24.11.0
