### PR TITLE
fix(core): show label prefix during BLE pairing

### LINKED ISSUE #6710: Trezor Safe 7 16-character device name max length not enforced on the device, and possibly causes a RSOD
**Describe the bug**
Fact:
When setting the device name on the Trezor Safe 7 using the builtin keyboard, the 16-character maximum length is not enforced. It is enforced when setting it from Windows.
Suspicion:
When the device name is set >16 characters, it seems to trigger a bug where the device throws a RSOD "HF @ 0x080DE5DE" every time Pair & Connect > Pair new device is tapped.
(I definitely encountered this bug and wiping the device & giving it a shorter name fixed it, but I can't prove causality.)

**Firmware version and revision**
Trezor Safe 7
Firmware version 2.11.0.0
Firmware type Universal
Bluetooth version 1.0.2.0

**Desktop/smartphone setup (please complete the following information):**
 - Wallet software: Trezor Suite
 - OS: Windows + Android
 - Browser: DuckDuckGo Browser
 - Version: latest from each

**To Reproduce**
1. Set the device name to "John's Trezor Safe 7" on-device.
2. Click Pair & Connect > Pair new device.
3. Encounter RSOD HF @ 0x080DE5DE.

**Expected behavior**
When the device name is set to >16 characters on the device, a validation failure occurs that prevents saving.
If the device name is >16 characters, RSOD HF @ 0x080DE5DE is not thrown.

**Screenshots**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by romanz**
Following https://satoshilabs.slack.com/archives/CL1D61PQF/p1775643967434449?thread_ts=1775632146.486079&cid=CL1D61PQF.

If the label is longer than 20 bytes, show the truncated version on BLE pairing screen.

# Note to QA:
Please try label like "1234567890123456789Ř". Not sure if it's allowed but if it is then the last letter should be removed and there should be no garbage as the last letter.

### CODE REVIEW

**Comment by romanz** [comment]
[Updated](https://github.com/trezor/trezor-firmware/compare/6565636385314aa2e33d44489dddd506b7206cff..ad0a980dad93b13f529acd4b63dfceebf2670fb6) `start_advertising()` docstring.

File: core/embed/rust/src/trezorhal/ble/mod.rs [hunk 1]
```diff
@@ -17,13 +19,25 @@ pub const TX_PACKET_SIZE: usize = ffi::BLE_TX_PACKET_SIZE as usize;
 const COMMAND_FAILED: Error = Error::RuntimeError(c"BLE command failed");
 const WRITE_FAILED: Error = Error::RuntimeError(c"BLE write failed");
 
+/// Valid UTF-8 `ADV_NAME_LEN` bytes prefix.
+pub struct AdvName<'a>(&'a str);
```
Comment (mmilata) [inline core/embed/rust/src/trezorhal/ble/mod.rs]: Why the wrapper? Is there any advantage over returning `&'a str`?

Comment (romanz) [reply core/embed/rust/src/trezorhal/ble/mod.rs]: I was trying to enforce calling `prefix_utf8_bytes()`, since it's the only function that constructs `AdvName`.
OTOH, it's probably not clear enough...

Comment (mmilata) [reply core/embed/rust/src/trezorhal/ble/mod.rs]: Ah, right, I guess it could work if there was also a constructor under `impl AdvName`. But passing the result to C makes it a bit ugly anyway imho.

Comment (romanz) [reply core/embed/rust/src/trezorhal/ble/mod.rs]: Removed `AdvName` in c404dfc500.

**Review by mmilata — APPROVED** [review]
LGTM, thanks!

**Comment by romanz** [comment]
Tested correct truncation of non-ASCII label `012345678901234567čřž`:

Screenshot from 2026-04-09 07-44-09

Screenshot from 2026-04-09 07-44-01

**Comment by Thalarion** [comment]
- device label `1234567890123456789Ř` showed up as `1234567890123456789` during BlueTooth pairing ✅
- label gets appropriately shortened when used for BT name
