### PR TITLE
Fix missing chunkification in bolt and caesar

### LINKED ISSUE #6279: Missing and incorrect chunkification in Bolt and Caesar
**Description**
The `confirm_address` function in **Bolt** and **Caesar** layout ignores the `chunkify` argument being passed causing missing chunkification in some Ethereum, NEM, Stellar, and other flows. [Reference](https://github.com/trezor/trezor-firmware/pull/6150/commits/b4b8c405492d992159a9f385b23d1d6cae0f3d7b)

The referred fixup undoes the fix in the PR for isolation and better investigation of a bad output being rendered, specifically in the case of [ **Stellar AccountMergeOp**](https://data.trezor.io/dev/firmware/ui_report/20472085846/diff/T2T1_en-device_tests-stellar-test_stellar.py%3A%3Atest_sign_tx%5BStellarAccountMergeOp%5D.html), is required.

Image

I have not found the root cause yet. Both these issues will be fixed under this ticket.

### PR DESCRIPTION
**Pull request by PrisionMike**
Fixes #6279 

**Root cause:**

- An edge case in `layout.rs` did not consider chunkification throwing incomplete 3-letter chunks instead of 4.
https://github.com/trezor/trezor-firmware/blob/963858c742da531d650d30a6bb4f931c76565b2d/core/embed/rust/src/ui/component/text/layout.rs#L763-L765
- The ellipsing and 'skipping last line' logic were not in sync. The latter used `is_last_line` flag which did not consider `style.line_spacing`. This however, made `is_last_line` unusable for page breaking as that should not include `line_spacing` space.

I decided to refactor the code to keep all chunkification together. The code still isn't perfect but more cohesive now, imo.

The chunk omission issue also existed in `Eckhart` when showing `Cardano` addresses and possibly other layouts. This issue was partially remedied in PRs #5946 and #5934. Further edge cases are resolved here.

CC: @overcat

### CODE REVIEW

File: core/embed/rust/src/ui/component/text/layout.rs
Comment (PrisionMike) [inline core/embed/rust/src/ui/component/text/layout.rs:1]: **Root cause:**
The if case on l776 did not consider chunkification throwing incomplete 3-letter chunks instead of 4.
I decided to refactor the code to keep all chunkification together. The code still isn't perfect but better, imo.

File: core/.changelog.d/6279.fixed [hunk 1]
```diff
@@ -0,0 +1 @@
+Fixed missing chunkification in Model T and Safe 3.
```
Comment (obrusvit) [inline core/.changelog.d/6279.fixed]: IIUC, it fixes it also for Safe 7? Let's write something like.
```
[T2T1,T2B1,T3B1,T3W1] Fixed chunkification in certain cases when showing an address.
```

Comment (PrisionMike) [reply core/.changelog.d/6279.fixed]: Done. Commit title and description will be updated during merge.

File: core/embed/rust/src/ui/component/text/layout.rs
Comment (romanz) [reply core/embed/rust/src/ui/component/text/layout.rs:1]: nit: it seems that line 776 at 3d46935da4 doesn't have an `if` statement:

Image

Could you please add a [commit-based URL](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet) to the problematic code?

File: core/embed/rust/src/ui/component/text/layout.rs [hunk 2]
```diff
@@ -386,8 +391,9 @@ impl TextLayout {
                 if span.insert_hyphen_before_line_break {
                     sink.hyphen(*cursor, self);
                 }
-                // Check the amount of vertical space we have left --- or manually force the
-                // next page.
+
+                // Cannot be is_last_line since it includes self.style.line_spacing which is
```
Comment (romanz) [inline core/embed/rust/src/ui/component/text/layout.rs:395]: Do you mean that `is_last_line` must be false here?

Asking since if `force_next_page` is true, `is_last_line` will be set to true as well - right?

File: core/embed/rust/src/ui/component/text/layout.rs [hunk 3]
```diff
@@ -386,8 +391,9 @@ impl TextLayout {
                 if span.insert_hyphen_before_line_break {
                     sink.hyphen(*cursor, self);
                 }
-                // Check the amount of vertical space we have left --- or manually force the
```
Comment (romanz) [inline core/embed/rust/src/ui/component/text/layout.rs:389]: Why was this comment removed?

File: core/embed/rust/src/ui/component/text/layout.rs (hunk 2 above)
Comment (PrisionMike) [reply core/embed/rust/src/ui/component/text/layout.rs:395]: Yeah. This is more because of the second part. The full condition is basically `is_last_line` minus the `line_spacing` refference. It errors when `force_next_page` is false and there is enough space for the subsequent characters, but it miscomputes and forces page break.

File: core/embed/rust/src/ui/component/text/layout.rs (hunk 3 above)
Comment (PrisionMike) [reply core/embed/rust/src/ui/component/text/layout.rs:389]: The new condition code felt rather self-explanatory.

File: core/embed/rust/src/ui/component/text/layout.rs
Comment (PrisionMike) [reply core/embed/rust/src/ui/component/text/layout.rs:1]: @romanz https://github.com/trezor/trezor-firmware/blob/963858c742da531d650d30a6bb4f931c76565b2d/core/embed/rust/src/ui/component/text/layout.rs#L763-L765
I was trying to comment at the line in the code itself but git doesn't let me comment at places I haven't changed. Permalink is from the current file in main.
