### PR TITLE
tearing effect prevention improvement

### LINKED ISSUE #2546: Tearing effect prevention on TT is not working properly
Current implementation of tearing effect prevention on TT is not correct: it synchronizes mcu with the LCD after drawing is done via `display_refresh` function, but there is no guarantee when the next drawing cycle will begin, therefore, it doesn't prevent tearing when sending data into display in the middle of panel refresh.

One solution is to introduce `display_sync` function, which should be called before drawing, which would wait until panel refresh completes (TE signal goes HI). The `display_refresh` should wait probably function as a guarantee that everything that was sent to display is shown on the LDC, therefore should wait for TE to go LO and then HI. 

This is still not bulletproof, as our drawing makes little guarantees about how much time it will take, but it should make nice improvement.

The `display_sync` could theoretically help to eliminating some otherwise hard to solve flickering, like button changing color when pressed, if we can send data to display fast enough. 

Note that the cycle is about 13ms long, so neither refresh or sync should be overused.

### PR DESCRIPTION
**Pull request by TychoVrahe**
Introduces `display_sync` function that synchronizes writing to display RAM with panel refresh. This is called before every relevant paint so that optimally the paint is done before the corresponding panel part is refreshed.

`display_orientation` function is modified so that the panel refresh direction respects the orientation. This is only possible for north and south orientation with current display driver. 

For west and east orientation, the display refresh direction is perpendicular to the orientation so the tearing effect prevention is not working and the effect is actually diagonal, but at least the display is synchronized so the UI should behave less randomly in this regard.

closes #2546 , builds on #2714

### CODE REVIEW

File: core/embed/extmod/modtrezorui/modtrezorui-display.h [hunk 1]
```diff
@@ -62,6 +62,17 @@ STATIC mp_obj_t mod_trezorui_Display_clear(mp_obj_t self) {
 STATIC MP_DEFINE_CONST_FUN_OBJ_1(mod_trezorui_Display_clear_obj,
                                  mod_trezorui_Display_clear);
 
+/// def sync(self) -> None:
```
Comment (matejcik) [inline core/embed/extmod/modtrezorui/modtrezorui-display.h:65]: Let's not expose it to Python at all and instead call it from Rust. `LayoutObj::paint_if_requested` seems like the right place.

Comment (TychoVrahe) [reply core/embed/extmod/modtrezorui/modtrezorui-display.h]: fixed https://github.com/trezor/trezor-firmware/commit/aaf6e751fc1de967251054c09e8dfbdb9d379eff

**Comment by TychoVrahe** [comment]
yeah it needs a rebase, homescreen image is not yet in this branch
