### PR TITLE
Fix: Center align shown pin for Eckhart

### LINKED ISSUE #5623: Chunkified text doesn't properly work in the TextLayout
##  Incomplete chunks at the end of the line

When using the `TextLayout` to render the left-aligned chunkified text, the text doesn't break only at the entire chunks, i.e.: 

Image

### Expected layout

```
8208  8811  1111
1111  11
```

### Root cause

`TextLayout` uses `Spans` to render the individual lines, in particular, the function `fit_horizontally`. The issue is that the function goes only character-by-character and doesn't look at the following characters to see if they would complete a chunk at the beginning of another line.

### Fix

We would have to predict if the entire chunk fits the line in the function `Span::fit_horizontally`

## Center and Right alignment do not work at all with chunkified text

When using the center alignment, the first chunk is rendered in the middle of the line, the second in the middle of the right half line, ..., until the text doesn't fit.

Image

### Severity

The `TextLayout` for the centered chunkified text is needed for the `Eckhart`'s PIN Keyboard screen: [Figma](https://www.figma.com/design/Dkl7W5PLqpr3TnXJ5hbnfd/--Future-Prod---Safe-7?node-id=11094-5812&t=7Xm7nQBSWalF82SG-0). For now, the left alignment is used.

### Root cause

The function`TextLayout::layout_text` uses `Spans` to render the individual lines. In the normal text, the `Span` corresponds to one line, and the alignment works properly. After the end of the span, the span is aligned in the remaining space. In the normal text, the remaining space is the entire line.
But in the case of the chunkified text, one span corresponds to one chunk because the chunk gap has to be rendered. This is also the reason for the strange rendering because:
The remaining space for the first chunk is the entire line, the remaining space for the second chunk is the right half of the line, ...

### Fix

The alignment should be done once per line, not after the each `Span` is processed.

### PR DESCRIPTION
**Pull request by PrisionMike**
Center align shown pin for Eckhart, as per design. Adding spaces instead of chunkification for spacing out the pin.
[no_changelog]
Fixes #5623

### CODE REVIEW

File: core/embed/rust/src/ui/component/text/layout.rs
Comment (PrisionMike) [inline core/embed/rust/src/ui/component/text/layout.rs:1]: Just a formatting commit. Not relevant to fix. Keeping `struct` and `impl` together.

File: core/embed/rust/src/strutil.rs [hunk 1]
```diff
@@ -84,6 +84,19 @@ pub fn format_pairing_code(code: u32, width: usize) -> ShortString {
     formatted_code
 }
 
+/// Adds spaces between characters. Output length is capped at 99 since
+/// ShortString is 50 characters long max. Example: "12345" becomes "1 2 3 4 5"
+pub fn space_out_str(pin: &str) -> String<99> {
```
Comment (obrusvit) [inline core/embed/rust/src/strutil.rs]: The bad thing about this is that it generates new variant for `String<T>` which takes some precious flash space. That's why we want to keep the generic type instantiations at minimum. We should think about a solution.
- are we able to make `space_out_str` return `'str` somehow? We may have to deal with some lifetime issues
- making `ShortString` to be `String<99>` instead of `String<50>`. That's bad because now we carry ~twice as much bytes everywhere.
- making `space_out_str` to be `Eckhart` specific so that it consumes flash space only there where we're not that limited
- ??

Comment (obrusvit) [reply core/embed/rust/src/strutil.rs]: Maybe you can compare binsizes of T3W1 before and after your change.

Comment (obrusvit) [reply core/embed/rust/src/strutil.rs]: Maybe we can revive and merge https://github.com/trezor/trezor-firmware/pull/4531 
cc @romanz and thanks for the suggestion.

Comment (romanz) [reply core/embed/rust/src/strutil.rs]: > making `space_out_str` to be `Eckhart` specific so that it consumes flash space only there where we're not that limited

I think it would be the simplest solution (for now), since rebasing & testing https://github.com/trezor/trezor-firmware/pull/4531 will probably take a while.

Comment (obrusvit) [reply core/embed/rust/src/strutil.rs]: Let's do so @PrisionMike 

I just tested on the device and it works nicely :+1:

Comment (PrisionMike) [reply core/embed/rust/src/strutil.rs]: Will need some reference but I think I can do that. I also have another idea of copying this routine to `pin.rs` where it is used. Since we only need it while rendering the pin, I can possibly get away with just using the RAM instead of invoking another type instantiation.

Comment (obrusvit) [reply core/embed/rust/src/strutil.rs]: @PrisionMike
> I also have another idea of copying this routine to pin.rs where it is used.

That's exactly what we meant. That will do the trick for now. Just remove your function `space_out_str` from `strutil.rs` and put it to `layout_eckhart/.../pin.rs`.

**Comment by PrisionMike** [comment]
no_changelog

**Comment by obrusvit** [comment]
After updating `fixtures.json` please squash the commits. Especially, we don't want "Revert" commits in the history.

**Comment by PrisionMike** [comment]
[no changelog]
