### PR TITLE
Eckhart homescreen improvements

### LINKED ISSUE #6501: Eckhart Homescreen improvements
We will employ the following Figma design to improve Eckhart UI (TS7) homescreen.

**Design:** [Figma](https://www.figma.com/design/Z1NtDTu70Dl8dJrpLK1IEE/Sandbox-TS-7?node-id=5014-37463&t=UykJTUNlGEw66BGE-4)

- [x] move `FuelGauge` into a permanent spot above the label
- [x] render Connection indicator next the `FuelGauge`
- [x] render Connection indicator in the DeviceMenu if appropriate
     - [x] Pair & Connect menu items should show the Connection indicator and "Connected" label based on wire/BT connection, not based on THP pairing status
- [x] change homescreen label
    - [x] different font size
    - [x] move the label next to the `FuelGauge` and Connection indicator
    - [x] draw a pill-shaped shadow behind `FuelGauge, Connection indicator and label (if custom homescreen is set)
    - [x] animate the label (Hide by default, Show on tap)
        - [x] exception: show initially by default after boot 
        - [ ] handle the `AttachType::Resume` scenario
- [x] Hint on the homescreen should have a pill-shaped shadow
    - [x] but no shadow on the default homescreen
- [x] Notification text should be rendered on the ActionBar if an extra action is available in the DeviceMenu (i.e. "PIN not set", "Backup needed" and "Backup failed")
- [x] "Backup failed" should show the homescreen without battery/connection indicator
- [x] animate the LED simulation on default homescreen (appear after some duration, stay for a while, then disappear)
- [ ] (Optional) label on the Homescreen should end in ellipsis so that the pill-shaped shadow doesn't go beyond the

### PR DESCRIPTION
**Pull request by obrusvit**
This PR changes the Eckhart UI (TS7) according to #6501 

# Notes for QA
- See the [Figma](https://www.figma.com/design/Z1NtDTu70Dl8dJrpLK1IEE/Sandbox-TS-7?node-id=5583-65045&t=5QNh8rNbYDMuB1Ic-11) and verify that it looks according to the designs.
- Verify that the Connection indicator shows accurately if bluetooth or USB is connected (both on the homescreen and in the device menu)
- Verify the label appearing/disappearing works on tap

### CODE REVIEW

File: core/embed/rust/src/ui/layout_eckhart/component/fuel_gauge.rs [hunk 1]
```diff
@@ -230,38 +240,24 @@ impl Component for FuelGauge {
...
                 }
             }
-            #[cfg(feature = "micropython")]
-            FuelGaugeMode::HomescreenBar(_) => {
-                shape::ToifImage::new(area.center(), icon.toif)
-                    .with_fg(color_icon)
-                    .with_align(Alignment2D::CENTER)
-                    .render(target);
-            }
             _ => {
```
Comment (romanz) [inline core/embed/rust/src/ui/layout_eckhart/component/fuel_gauge.rs]: nit: consider specifying the remaining variants explicitly

```suggestion
            FuelGaugeMode::AlwaysFull | FuelGaugeMode::OnChargingChange(_) => {
```

File: core/embed/rust/src/ui/layout_eckhart/component/connection_indicator.rs [hunk 2]
```diff
@@ -0,0 +1,101 @@
...
+                self.connected = usb::usb_configured() || ble::is_connected();
+            }
+            Event::USB(USBEvent::Configured) => {
+                self.connected = true;
+            }
+            Event::USB(USBEvent::Deconfigured) => {
+                // Only update if BLE is also disconnected
+                self.connected = ble::is_connected();
+            }
+            Event::BLE(BLEEvent::Connected) => {
```
Comment (romanz) [inline core/embed/rust/src/ui/layout_eckhart/component/connection_indicator.rs:82]: nit: annotate `Event::BLE(_)` variants with with `#[cfg(feature = "ble")]`?

File: core/embed/rust/src/ui/layout_eckhart/component/fuel_gauge.rs [hunk 3]
```diff
@@ -69,49 +78,70 @@ impl FuelGauge {
...
+            #[cfg(feature = "micropython")]
+            FuelGaugeMode::OnChargingChange(timer) => timer.is_running(),
         }
     }
 
+    /// Returns the total rendered width of the fuel gauge content.
+    pub fn content_width(&self) -> i16 {
+        let icon_w = self.icon_width();
+        match self.mode {
+            FuelGaugeMode::AlwaysIconOnly | FuelGaugeMode::ChargingIconOnly => icon_w,
```
Comment (romanz) [inline core/embed/rust/src/ui/layout_eckhart/component/fuel_gauge.rs]: nit: consider adding `fn is_icon_only(&self) -> bool` method to `FuelGaugeMode`.

File: core/embed/rust/src/ui/layout_eckhart/component/fuel_gauge.rs [hunk 4]
```diff
@@ -69,49 +78,70 @@ impl FuelGauge {
...
+                matches!(self.charging_state, ChargingState::Charging)
             }
+            #[cfg(feature = "micropython")]
+            FuelGaugeMode::OnChargingChange(timer) => timer.is_running(),
         }
     }
 
+    /// Returns the total rendered width of the fuel gauge content.
+    pub fn content_width(&self) -> i16 {
+        let icon_w = self.icon_width();
```
Comment (romanz) [inline core/embed/rust/src/ui/layout_eckhart/component/fuel_gauge.rs]: nit: (rename & reuse cached icon)

```suggestion
        let icon_width = self.battery_indication.0.toif.width();
```

File: core/embed/rust/src/ui/layout_eckhart/component/fuel_gauge.rs [hunk 5]
```diff
@@ -69,49 +78,70 @@ impl FuelGauge {
...
-        self.font = font;
-        self
-    }
-
     pub fn update_pm_state(&mut self) {
         self.soc = Some(power_manager::soc());
         self.charging_state = power_manager::charging_state();
+        self.soc_text = match self.soc {
+            Some(soc) => uformat!("{} %", soc),
+            None => uformat!("?"),
```
Comment (romanz) [inline core/embed/rust/src/ui/layout_eckhart/component/fuel_gauge.rs]: Do we need the `None` variant here? (since `self.soc` is assigned to `Some(...)` above)

File: core/embed/rust/src/ui/layout_eckhart/component/fuel_gauge.rs [hunk 6]
```diff
@@ -69,49 +78,70 @@ impl FuelGauge {
...
+    /// Returns the total rendered width of the fuel gauge content.
+    pub fn content_width(&self) -> i16 {
+        let icon_w = self.icon_width();
+        match self.mode {
+            FuelGaugeMode::AlwaysIconOnly | FuelGaugeMode::ChargingIconOnly => icon_w,
+            _ => icon_w + ICON_PERCENT_GAP + self.font.text_width(&self.soc_text),
+        }
+    }
+
+    const fn icon_width(&self) -> i16 {
```
Comment (romanz) [inline core/embed/rust/src/ui/layout_eckhart/component/fuel_gauge.rs]: Consider removing if not used elsewhere.

File: core/embed/rust/src/ui/layout_eckhart/component/fuel_gauge.rs [hunk 7]
```diff
@@ -69,49 +78,70 @@ impl FuelGauge {
...
+        match self.charging_state {
+            ChargingState::Charging => ICON_BATTERY_ZAP.toif.width(),
+            ChargingState::Discharging | ChargingState::Idle => ICON_BATTERY_FULL.toif.width(),
+        }
+    }
+
+    fn render_icon<'s>(
+        &self,
+        area: Rect,
```
Comment (romanz) [inline core/embed/rust/src/ui/layout_eckhart/component/fuel_gauge.rs]: nit: no need to pass `icon` & `color` via arguments (they are cached in `self.battery_indication`)

File: core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs [hunk 8]
```diff
@@ -190,70 +139,496 @@ impl Component for Homescreen {
...
+impl HomescreenNotificationCenter {
+    pub fn new(
+        notification: Option<Notification>,
+        locked: bool,
+        coinjoin_authorized: bool,
+        background_image: bool,
+    ) -> Self {
+        // If there's a notification which has an entry in the DeviceMenu
+        let actionable_notification = notification.as_ref().is_some_and(|n| {
+            // TODO: consider passing the "actionable" flag from the application layer
```
Comment (romanz) [inline core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs]: nit: maybe make `actionable: bool` field part of the `Notification` struct?

File: core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs [hunk 9]
```diff
@@ -190,70 +139,496 @@ impl Component for Homescreen {
...
+    pub fn homebar_style(&self) -> (ButtonStyleSheet, Gradient) {
+        let level = self.notification.as_ref().map(|n| n.level);
+        button_homebar_style(level.as_ref(), self.actionable_notification)
+    }
+
+    fn notification_level(&self) -> Option<NotificationLevel> {
+        self.notification.as_ref().map(|n| n.level)
+    }
+
+    fn get_notification_led_color(n: &Notification) -> Color {
```
Comment (romanz) [inline core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs:279]: nit: consider moving to `Notification::get_led_color()`

File: core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs [hunk 10]
```diff
@@ -190,70 +139,496 @@ impl Component for Homescreen {
...
+        match n.level {
+            NotificationLevel::Alert => theme::LED_RED,
+            NotificationLevel::Warning => theme::LED_YELLOW,
+            NotificationLevel::Info => theme::LED_BLUE,
+            NotificationLevel::Success => theme::LED_GREEN_LIGHT,
+        }
+    }
+
+    fn get_notification_hint(n: &Notification) -> Hint<'static> {
```
Comment (romanz) [inline core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs:288]: nit: consider moving to `Notification::get_hint()`

File: core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs [hunk 11]
```diff
@@ -190,70 +139,496 @@ impl Component for Homescreen {
...
+            None
+        };
+        ButtonContent::HomeBar(text)
+    }
+    pub fn homebar_style(&self) -> (ButtonStyleSheet, Gradient) {
+        let level = self.notification.as_ref().map(|n| n.level);
+        button_homebar_style(level.as_ref(), self.actionable_notification)
+    }
+
+    fn notification_level(&self) -> Option<NotificationLevel> {
```
Comment (romanz) [inline core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs:269]: nit: consider inlining if used only once

File: core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs [hunk 12]
```diff
@@ -190,70 +139,496 @@ impl Component for Homescreen {
...
+            hint,
+            hint_shadow_area: Rect::zero(),
+            led_color,
+            led_active: false,
+            led_timer: Timer::new(),
+            background_image,
+        }
+    }
+
+    pub fn homebar_content(&self, bootscreen: bool, locked: bool) -> ButtonContent {
```
Comment (romanz) [inline core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs]: nit: can we merge `homebar_content()` and `homebar_style()` into:
```
    pub fn homebar_button(&self, bootscreen: bool, locked: bool) -> Button
```

File: core/embed/rust/src/ui/layout_eckhart/component/connection_indicator.rs (hunk 2 above)
Comment (romanz) [reply core/embed/rust/src/ui/layout_eckhart/component/connection_indicator.rs:82]: https://github.com/trezor/trezor-firmware/actions/runs/23326579113/job/67848925231

File: core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs [hunk 13]
```diff
@@ -190,70 +139,496 @@ impl Component for Homescreen {
...
+    /// Whether the notification is actionable (i.e. has a corresponding entry
+    /// in the DeviceMenu)
+    actionable_notification: bool,
+    /// Notification text display
+    hint: Option<Hint<'static>>,
+    hint_shadow_area: Rect,
+    /// LED color
+    led_color: Option<Color>,
+    /// Whether the LED is currently active
+    led_active: bool,
```
Comment (romanz) [inline core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs:197]: Can we replace `led_active` by `led_color.is_some()`?

File: core/embed/rust/src/ui/layout_eckhart/component/button.rs [hunk 14]
```diff
@@ -56,6 +59,7 @@ pub struct Button {
     long_timer: Timer,
     haptic: HapticMode,
     subtext_marquee: Option<Marquee>,
+    connection_indicator: Option<ConnectionIndicator>,
```
Comment (romanz) [inline core/embed/rust/src/ui/layout_eckhart/component/button.rs:62]: Adding `connection_indicator` here causes `Button` size to increase by 10 bytes
```
print-type-size type: `ui::layout_eckhart::component::button::Button`: 156 bytes, alignment: 4 bytes
print-type-size     field `.subtext_marquee`: 64 bytes
print-type-size     field `.content`: 32 bytes
print-type-size     field `.radius_or_gradient`: 4 bytes
print-type-size     field `.stylesheet`: 12 bytes
print-type-size     field `.area`: 8 bytes
print-type-size     field `.touch_expand`: 8 bytes
print-type-size     field `.content_offset`: 4 bytes
print-type-size     field `.long_timer`: 4 bytes
print-type-size     field `.connection_indicator`: 10 bytes
print-type-size     field `.long_press`: 2 bytes
print-type-size     field `.long_press_danger`: 1 bytes
print-type-size     field `.skip_test_visit`: 1 bytes
print-type-size     field `.text_align`: 1 bytes
print-type-size     field `.haptic`: 1 bytes
print-type-size     field `.state`: 1 bytes
print-type-size     end padding: 3 bytes
```
-> `LongMenuGc` size is increased by 1kB:
```
print-type-size type: `heapless::Vec<ui::layout_eckhart::component::button::Button, 100>`: 15604 bytes, alignment: 4 bytes
print-type-size     field `.buffer`: 15600 bytes
print-type-size     field `.len`: 4 bytes
```

File: core/embed/rust/src/ui/layout_eckhart/component/button.rs [hunk 15]
```diff
@@ -205,12 +216,18 @@ impl Button {
...
     ) -> Self {
-        Self::new(ButtonContent::clipped_text_and_subtext(
+        let mut button = Self::new(ButtonContent::clipped_text_and_subtext(
             text,
             subtext,
             subtext_style,
-        ))
+            connected_indicator,
+        ));
+        if connected_indicator {
```
Comment (romanz) [inline core/embed/rust/src/ui/layout_eckhart/component/button.rs:228]: nit (consider renaming for consistency):

```suggestion
        if connection_indicator {
```

File: core/embed/rust/src/ui/layout_eckhart/component/button.rs [hunk 16]
```diff
@@ -693,14 +713,40 @@ impl Component for Button {
...
+                        ),
+                        Offset::new(ci_size, ci_size),
+                    );
+                    ci.place(ci_area);
+                }
+            }
+
             if let Some(m) = self.subtext_marquee.as_mut() {
+                let indicator_offset = if let Some(ci) = &self.connection_indicator {
+                    ci.content_width() + 12
```
Comment (romanz) [inline core/embed/rust/src/ui/layout_eckhart/component/button.rs]: why 12? :)

File: core/embed/rust/src/ui/component/marquee.rs [hunk 17]
```diff
@@ -23,7 +23,7 @@ enum State {
 }
 
 pub struct Marquee {
-    area: Rect,
+    pub area: Rect,
```
Comment (romanz) [inline core/embed/rust/src/ui/component/marquee.rs]: Not sure if `pub` here is needed - the code seems to build without it.

```suggestion
    area: Rect,
```

File: core/embed/rust/src/ui/layout_eckhart/firmware/device_menu_screen.rs [hunk 18]
```diff
@@ -326,6 +329,7 @@ impl DeviceMenuScreen {
         screen.register_power_menu();
 
         let is_connected = connected_idx.is_some_and(|idx| usize::from(idx) < paired_devices.len());
+        let is_connected = is_connected || usb::usb_configured();
```
Comment (romanz) [inline core/embed/rust/src/ui/layout_eckhart/firmware/device_menu_screen.rs]: Shouldn't we use `ble::is_connected()` (similar to `ConnectionIndicator`)?

File: core/src/apps/homescreen/device_menu.py [hunk 19]
```diff
@@ -116,7 +117,8 @@ async def handle_device_menu() -> None:
         firmware_type = "Bitcoin-only" if utils.BITCOIN_ONLY else "Universal"
         production_year = _get_production_year()
 
-        menu_result = await interact(
+        workflow.close_others()
```
Comment (romanz) [inline core/src/apps/homescreen/device_menu.py]: Why not to use `interact()`?

File: core/src/apps/homescreen/device_menu.py [hunk 20]
```diff
@@ -153,9 +155,11 @@ async def handle_device_menu() -> None:
                 ],
                 production_year=production_year,
             ),
-            "device_menu",
-            raise_on_cancel=None,
         )
+        try:
+            menu_result = await obj.get_result()
+        finally:
+            obj.__del__()
```
Comment (romanz) [inline core/src/apps/homescreen/device_menu.py]: Is there a reason to call `__del__()` explicitly?

**Comment by romanz** [comment]
Tested with 8887a1d0de merged - LGTM, except the homescreen seems to flicker when unsuspending the device:
https://drive.google.com/file/d/11SBFnFRAJulYEQ_JzbiSGJuG3Ev2WiQH/

File: core/embed/rust/src/ui/layout_eckhart/component/fuel_gauge.rs (hunk 3 above)
Comment (obrusvit) [reply core/embed/rust/src/ui/layout_eckhart/component/fuel_gauge.rs]: I'd prefer listing the enum in this case.

File: core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs (hunk 9 above)
Comment (obrusvit) [reply core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs:279]: `Notification` is supposed to be generic over all layouts whereas this is Eckhart specific. Maybe we can feature-guard it but then we should include similar functions also from other layouts. I'd keep it here for now.

File: core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs (hunk 10 above)
Comment (obrusvit) [reply core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs:288]: Similarly to the above.
`Notification` is supposed to be generic over all layouts whereas this is Eckhart specific.

File: core/embed/rust/src/ui/layout_eckhart/component/fuel_gauge.rs (hunk 1 above)
Comment (obrusvit) [reply core/embed/rust/src/ui/layout_eckhart/component/fuel_gauge.rs]: https://github.com/trezor/trezor-firmware/pull/6543/changes/d1d73037bd35fe1ed52c93dc43f60209ef368b16

File: core/embed/rust/src/ui/layout_eckhart/component/connection_indicator.rs (hunk 2 above)
Comment (obrusvit) [reply core/embed/rust/src/ui/layout_eckhart/component/connection_indicator.rs:82]: guarded all usage: https://github.com/trezor/trezor-firmware/pull/6543/changes/be3cea1d821862dbdac094ef90da46ac011976ad

File: core/embed/rust/src/ui/layout_eckhart/component/fuel_gauge.rs (hunk 4 above)
Comment (obrusvit) [reply core/embed/rust/src/ui/layout_eckhart/component/fuel_gauge.rs]: https://github.com/trezor/trezor-firmware/pull/6543/changes/42986a8bb1ab13861641c5712249e6da3becab3d

File: core/embed/rust/src/ui/layout_eckhart/component/fuel_gauge.rs (hunk 6 above)
Comment (obrusvit) [reply core/embed/rust/src/ui/layout_eckhart/component/fuel_gauge.rs]: https://github.com/trezor/trezor-firmware/pull/6543/changes/42986a8bb1ab13861641c5712249e6da3becab3d

File: core/embed/rust/src/ui/layout_eckhart/component/fuel_gauge.rs (hunk 7 above)
Comment (obrusvit) [reply core/embed/rust/src/ui/layout_eckhart/component/fuel_gauge.rs]: https://github.com/trezor/trezor-firmware/pull/6543/changes/42986a8bb1ab13861641c5712249e6da3becab3d

File: core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs (hunk 12 above)
Comment (obrusvit) [reply core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs]: Yes, good idea.
https://github.com/trezor/trezor-firmware/pull/6543/changes/646aabe2c2c0c61dc7b52cd5acbaf89e17edc364

File: core/embed/rust/src/ui/layout_eckhart/component/button.rs (hunk 15 above)
Comment (obrusvit) [reply core/embed/rust/src/ui/layout_eckhart/component/button.rs:228]: https://github.com/trezor/trezor-firmware/pull/6543/changes/3b1ca66d00c25509fa454763ce98ed51d02faaa5

File: core/embed/rust/src/ui/component/marquee.rs (hunk 17 above)
Comment (obrusvit) [reply core/embed/rust/src/ui/component/marquee.rs]: https://github.com/trezor/trezor-firmware/pull/6543/changes/0789657d69398f5141f9655046b596adbbff5c69

File: core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs
Comment (romanz) [inline core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs:1]: nit: consider splitting this file (e.g. into a `homescreen` module)

File: core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs [hunk 21]
```diff
@@ -190,70 +136,497 @@ impl Component for Homescreen {
...
+            }
+            self.fuel_gauge.render(target);
+            self.connection_indicator.render(target);
+        } else {
+            self.label.render(target);
+        }
+    }
+}
+
+static mut FIRST_BOOT: bool = true;
```
Comment (romanz) [inline core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs]: nit: consider using `AtomicBool` (to avoid `unsafe` below)?

File: core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs [hunk 22]
```diff
@@ -190,70 +136,497 @@ impl Component for Homescreen {
...
+
+struct ShowLabelAnimation {
+    pub stopwatch: Stopwatch,
+    pub timer: Timer,
+    pub duration: Duration,
```
Comment (romanz) [inline core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs]: nit: can those fields be private?

File: core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs [hunk 23]
```diff
@@ -190,70 +136,497 @@ impl Component for Homescreen {
...
+                false
+            } else {
+                !animation_disabled()
+            }
+        };
+
+        Self {
+            stopwatch: Stopwatch::default(),
+            timer: Timer::new(),
+            duration: Duration::from_millis((label_width as u32 * 300) / 120),
```
Comment (romanz) [inline core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs]: Please explain the `* 300 / 120` part :)

File: core/src/apps/homescreen/device_menu.py (hunk 19 above)
Comment (obrusvit) [reply core/src/apps/homescreen/device_menu.py]: The reason is `interact` takes `LayoutObj` (Rust-side layout handler) whereas the `UsbAwareLayout` inherits from `Layout` (python-side runner).

`interact` wraps the `LayoutObj` into `Layout` and starts the layout.

We can maybe introduce a new argument to `interact` which would make the function wrap into another runner (i.e. `UsbAwareLayout` in this case) or we can keep the current behavior. WDYT

File: core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs [hunk 24]
```diff
@@ -190,70 +136,497 @@ impl Component for Homescreen {
...
+
+    fn is_active(&self) -> bool {
+        self.stopwatch.is_running_within(self.duration)
+    }
+
+    fn reset(&mut self) {
+        self.stopwatch = Stopwatch::default();
+    }
+
+    fn change_dir(&mut self) {
```
Comment (romanz) [inline core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs:586]: Not sure about the naming of this method - i.e. which direction is being changed?

File: core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs [hunk 25]
```diff
@@ -190,70 +136,497 @@ impl Component for Homescreen {
...
+    animating: bool,
+    hidden: bool,
+    /// When true, the label slides in/out. When false, it instantly
+    /// shows/hides.
+    animated: bool,
+}
+
+impl ShowLabelAnimation {
+    const HIDE_AFTER: Duration = Duration::from_millis(3000);
+    const MOVE_DURATION: Duration = Duration::from_millis(500);
```
Comment (romanz) [inline core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs:551]: unused

File: core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs (hunk 13 above)
Comment (obrusvit) [reply core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs:197]: No because the `led_color` dictates the color whereas `led_active` holds information whether it's currently turned on. We can have a situation where `led_color` is set and `led_active` toggles after some time due to the "animated" LED lightning simulation.

File: core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs (hunk 24 above)
Comment (obrusvit) [reply core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs:586]: If the label is in the process of hiding (animating) and a user taps the screen, this function changes the direction of the animation so that it starts "showing" again.

File: core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs (hunk 8 above)
Comment (obrusvit) [reply core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs]: I pass it from python as the TODO said

https://github.com/trezor/trezor-firmware/pull/6543/commits/7169c36dc9a71eaf873c4e8d8cbd0a16952304b4

File: core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs [hunk 26]
```diff
@@ -190,70 +139,496 @@ impl Component for Homescreen {
...
+        let actionable_notification = notification.as_ref().is_some_and(|n| {
+            // TODO: consider passing the "actionable" flag from the application layer
+            matches!(
+                n.text,
+                text if text == TR::homescreen__title_pin_not_set.into()
+                    || text == TR::homescreen__title_backup_needed.into()
+                    || text == TR::homescreen__title_backup_failed.into()
+            )
+        });
+
```
[the remark this answers is not in the document]
Comment (obrusvit) [reply core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs:217]: https://github.com/trezor/trezor-firmware/pull/6543/commits/7169c36dc9a71eaf873c4e8d8cbd0a16952304b4

File: core/embed/rust/src/ui/layout_eckhart/firmware/hint.rs [hunk 27]
```diff
@@ -160,13 +161,20 @@ impl<'a> HintContent<'a> {
...
+    }
+
     fn render<'s>(&'s self, area: Rect, target: &mut impl Renderer<'s>)
     where
         's: 'a,
     {
         match self {
             HintContent::Instruction(instruction) => instruction.render(target, area),
-            HintContent::PageCounter(page_counter) => page_counter.render(target, area),
+            HintContent::PageCounter(page_counter) => page_counter.render(target),
```
[the remark this answers is not in the document]
Comment (obrusvit) [reply core/embed/rust/src/ui/layout_eckhart/firmware/hint.rs:182]: Fixed here: https://github.com/trezor/trezor-firmware/pull/6543/changes/c68871eac9170f09aed070a640fe466e5d4566cb

File: core/embed/rust/src/ui/layout_eckhart/component/fuel_gauge.rs (hunk 5 above)
Comment (obrusvit) [reply core/embed/rust/src/ui/layout_eckhart/component/fuel_gauge.rs]: https://github.com/trezor/trezor-firmware/pull/6543/changes/0b23cd78d021e0f1c40a958771b14458ab680249

File: core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs (hunk 23 above)
Comment (obrusvit) [reply core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs]: I took it over from a similar code in Delizia, https://github.com/trezor/trezor-firmware/blob/a677eeff205663dcf1b9a4661abd7e5ca972efb7/core/embed/rust/src/ui/layout_delizia/component/homescreen.rs#L333

But I changed it to use the move duration and reference width here: https://github.com/trezor/trezor-firmware/pull/6543/commits/c13dfc40a7c901706e7047d3d3cb581999b0971a

File: core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs (hunk 25 above)
Comment (obrusvit) [reply core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs:551]: used here: https://github.com/trezor/trezor-firmware/pull/6543/commits/c13dfc40a7c901706e7047d3d3cb581999b0971a

File: core/embed/rust/src/ui/layout_eckhart/firmware/device_menu_screen.rs (hunk 18 above)
Comment (obrusvit) [reply core/embed/rust/src/ui/layout_eckhart/firmware/device_menu_screen.rs]: I believe so: https://github.com/trezor/trezor-firmware/pull/6543/changes/a4fded19babdf3060aac5eaac5ea60a682724344

File: core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs (hunk 22 above)
Comment (obrusvit) [reply core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs]: https://github.com/trezor/trezor-firmware/pull/6543/commits/120810c4a4247c784828cbba9744d52f4659a5ce

File: core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs (hunk 21 above)
Comment (obrusvit) [reply core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs]: https://github.com/trezor/trezor-firmware/pull/6543/commits/8b8821b71709467f0990fa7d530d90a47e450d9f

Comment (obrusvit) [reply core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs]: https://github.com/trezor/trezor-firmware/pull/6543/commits/8b8821b71709467f0990fa7d530d90a47e450d9f

File: core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs (hunk 11 above)
Comment (obrusvit) [reply core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs:269]: I'd keep it but I also changed the function to `NotificationCenter::is_alert()`
https://github.com/trezor/trezor-firmware/pull/6543/commits/943d8e6e67f6bbb89429bc46b8c6f76ac81c033a

File: core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs [hunk 28]
```diff
@@ -190,70 +137,487 @@ impl Component for Homescreen {
...
+        let label_anim = Some(ShowLabelAnimation::new(text_width, background_image));
+
         Self {
-            label: label_primary,
-            label_shadow,
+            area: Rect::zero(),
+            label: Label::left_aligned(label, style).top_aligned(),
+            fuel_gauge: FuelGauge::always_icon_only(),
+            connection_indicator: ConnectionIndicator::new(),
+            background_image,
```
[the remark this answers is not in the document]
Comment (obrusvit) [reply core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs:426]: I changed it to `new_polled()` on rebase.

File: core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs [hunk 29]
```diff
@@ -190,70 +137,487 @@ impl Component for Homescreen {
...
+
+    fn event(&mut self, ctx: &mut EventCtx, event: Event) -> Option<Self::Msg> {
+        if self.show_indicators {
+            self.fuel_gauge.event(ctx, event);
+            let connection_event = self.connection_indicator.event(ctx, event);
+            if matches!(event, Event::PM(_)) || connection_event.is_some() {
+                // TODO: could FuelGauge also return Some(()) on update?
+                self.place(self.area);
+                ctx.request_paint();
+            }
```
[the remark this answers is not in the document]
Comment (obrusvit) [reply core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs:496]: This does not seem as an issue.

File: core/embed/rust/src/ui/layout_eckhart/component/button.rs (hunk 16 above)
Comment (obrusvit) [reply core/embed/rust/src/ui/layout_eckhart/component/button.rs]: I changed it to a named constant on rebase.

File: core/embed/rust/src/ui/layout_eckhart/component/fuel_gauge.rs (hunk 5 above)
Comment (romanz) [reply core/embed/rust/src/ui/layout_eckhart/component/fuel_gauge.rs]: Can we make `self.soc` an non-optional `u8`?

File: core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs (hunk 24 above)
Comment (romanz) [reply core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs:586]: Got it - thanks!

File: core/src/apps/homescreen/device_menu.py (hunk 19 above)
Comment (romanz) [reply core/src/apps/homescreen/device_menu.py]: I would suggest https://github.com/trezor/trezor-firmware/compare/obrusvit/eckhart/hs-improvements...romanz/hs-interact

File: core/src/apps/homescreen/device_menu.py (hunk 20 above)
Comment (obrusvit) [reply core/src/apps/homescreen/device_menu.py]: Cherry-picked your suggestion: https://github.com/trezor/trezor-firmware/pull/6543/commits/b0db5c01d1b57a83ae5749e62e55bc25cdad204a

File: core/src/apps/homescreen/device_menu.py (hunk 19 above)
Comment (obrusvit) [reply core/src/apps/homescreen/device_menu.py]: https://github.com/trezor/trezor-firmware/pull/6543/commits/b0db5c01d1b57a83ae5749e62e55bc25cdad204a

File: core/embed/rust/src/ui/layout_eckhart/component/fuel_gauge.rs (hunk 5 above)
Comment (obrusvit) [reply core/embed/rust/src/ui/layout_eckhart/component/fuel_gauge.rs]: https://github.com/trezor/trezor-firmware/pull/6543/commits/411bf780c5734070bd651c32cdc5e7675ae1d711

File: core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs [hunk 30]
```diff
@@ -113,6 +145,19 @@ impl Component for Homescreen {
         self.header.event(ctx, event);
         self.notification_center.event(ctx, event);
 
+        // Swap action bar to notification style when notification becomes visible
+        if !self.action_bar_swapped && self.notification_center.notification_visible {
```
Comment (romanz) [inline core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs]: Can it be simplified using https://github.com/trezor/trezor-firmware/commit/7a416baf1520efd848a474cd4ab5c07573659d55?

**Review by romanz — APPROVED** [review]
LGTM

File: core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs (hunk 30 above)
Comment (obrusvit) [reply core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs]: did so and rebased already https://github.com/trezor/trezor-firmware/pull/6543/commits/4a8cfdac293eb2aaef3f305fb3d6da857eea4165

**Comment by Thalarion** [comment]
Validated homescreen improvement against Figma designs.

- label shows up on tap, then disappears ✅
  - label slides out and in on custom wallpaper ✅
- connection indicator is shown on homescreen and in device menu (in two places - under Pair & Connect and in case of BT under the device Trezor is connected to) for both USB and BT connections ✅
- battery indicator is shown on homescreen and in device menu with battery percentage ✅
- warning and error screens
  - yellow warning on the action bar with no other changes ✅
  - red error on the action bar with homescreen showing no battery/connection indicator ✅

Issues found:

1. Vertical alignment of the Trezor device name in relation to the connection indicator is slightly off. The text should be lower by about 1 px. The designs show it vertically centered. In comparison, the vertical alignment relative to the green dot seems correct for the _Connection_ text in device menu.

image

2. When charging stars the connection indicator jumps further to the right than it should and stays there.

https://github.com/user-attachments/assets/2274de22-193b-4a32-9e83-2602ac052264

Not tested:
- battery error states

**Comment by obrusvit** [comment]
@lapohoda Please check the report above. We can fix it for the next release.

**Comment by lapohoda** [comment]
@obrusvit

1 / 1 px down will do the job:
image

2 / correct, it shouldn't be jumping.

**Comment by obrusvit** [comment]
https://github.com/trezor/trezor-firmware/pull/6702

File: core/embed/rust/src/ui/layout_eckhart/component/button.rs (hunk 14 above)
Comment (obrusvit) [reply core/embed/rust/src/ui/layout_eckhart/component/button.rs:62]: @copilot create an issue which should track this problem. Write in the description that we should improve the code so that the `Button` takes less space in memory and potentially create a more `AdvancedButton` which could hold the connection status.

File: core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs
Comment (obrusvit) [reply core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs:1]: @copilot create an issue to split `homescreen` module into separate submodules.

File: core/embed/rust/src/ui/layout_eckhart/component/button.rs (hunk 14 above)
Comment (obrusvit) [reply core/embed/rust/src/ui/layout_eckhart/component/button.rs:62]: @coderabbitai create an issue which should track this problem. Write in the description that we should improve the code so that the Button takes less space in memory and potentially create a more AdvancedButton which could hold the connection status.

File: core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs
Comment (obrusvit) [reply core/embed/rust/src/ui/layout_eckhart/firmware/homescreen.rs:1]: @coderabbitai create an issue to split homescreen module into separate submodules.
